# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "com.vaadin.hilla:*"
      - dependency-name: "com.vaadin:*"
  - package-ecosystem: "maven"
    directory: "/"
    target-branch: "24.4"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "com.vaadin.hilla:*"
        update-types: [ "version-update:semver-major", "version-update:semver-minor"]
      - dependency-name: "com.vaadin:*"
        update-types: [ "version-update:semver-major", "version-update:semver-minor"]
  - package-ecosystem: "maven"
    directory: "/"
    target-branch: "2.5"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "dev.hilla:*"
        update-types: [ "version-update:semver-major", "version-update:semver-minor"]
      - dependency-name: "com.vaadin:*"
        update-types: [ "version-update:semver-major", "version-update:semver-minor"]
      - dependency-name: "io.quarkus*:*"
        update-types: [ "version-update:semver-major"]
  - package-ecosystem: "maven"
    directory: "/"
    target-branch: "1.3"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "dev.hilla:*"
        update-types: [ "version-update:semver-major", "version-update:semver-minor"]
      - dependency-name: "com.vaadin:*"
        update-types: [ "version-update:semver-major", "version-update:semver-minor"]
      - dependency-name: "io.quarkus*:*"
        update-types: [ "version-update:semver-major"]
