#!/usr/bin/env bash
set -e

#MNV_OPTS="--settings .github/quarkus-ecosystem-maven-settings.xml -B -e -V -ntp -DtrimStackTrace=false"
MNV_OPTS="-B -e -V -ntp -DtrimStackTrace=false"
# update the versions
mvn ${MNV_OPTS} -N versions:set-property -Dproperty=${QUARKUS_VERSION_POM_PROPERTY} -DnewVersion=${QUARKUS_VERSION} -DgenerateBackupPoms=false

# run the tests
echo "Build"
mvn ${MNV_OPTS} -DskipTests install

echo "Test"
mvn ${MNV_OPTS} verify

echo "End-to-end Test (Development mode)"
mvn ${MNV_OPTS} -Dselenide.browserBinary=${SELENIDE_BROWSER_BINARY} -Pit-tests verify

echo "End-to-end Test (Production mode)"
mvn ${MNV_OPTS} -Dselenide.browserBinary=${SELENIDE_BROWSER_BINARY} -Pit-tests,production verify

