vaadin.whitelisted-packages = com.vaadin,org.vaadin,com.example.application
quarkus.rest.jackson.optimization.enable-reflection-free-serializers=false
quarkus.log.category."com.vaadin.hilla".level=DEBUG
