name: 'run-validation'
description: 'Build and test'
inputs:
  ref:
    description: >
      The branch, tag or SHA to checkout. Defaults to github.ref.
    required: true
    default: ${{ github.ref }}
  original_ref:
    description: >
      The branch, tag or SHA to checkout after the build completes. Defaults to github.ref.
    default: ${{ github.ref }}
  java_version:
    description: 'Java version'
    required: true
  hilla_version:
    description: 'Hilla version'
    required: true
runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ inputs.ref }}
        fetch-depth: 0
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        java-version: ${{ inputs.java_version }}
        distribution: 'temurin'
        cache: maven
    - uses: browser-actions/setup-chrome@latest
      id: setup-chrome
      with:
        chrome-version: stable
    - name: Build
      shell: bash
      run: |
        set -x -e -o pipefail
        mvn -N versions:set-property -Dproperty=hilla.version -DnewVersion=${{ inputs.hilla_version }} -DgenerateBackupPoms=false
        vaadin_version=$(mvn -ntp -N -Pdetect-vaadin-platform -q)-SNAPSHOT
        mvn versions:set-property -Dproperty=vaadin.version -DnewVersion=$vaadin_version -DgenerateBackupPoms=false -Pit-tests
        echo "Running Validation with Hilla ${{ inputs.hilla_version }} and Vaadin $vaadin_version">> "$GITHUB_STEP_SUMMARY"
        mvn -V -e -B -ntp -DskipTests -Dmaven.javadoc.skip=false install
    - name: Test
      shell: bash
      run: |
        set -x -e -o pipefail
        mvn -V -e -B -ntp verify -Dmaven.javadoc.skip=false -DtrimStackTrace=false
    - name: End-to-end Tests (Development mode)
      shell: bash
      run: |
        set -x -e -o pipefail
        mvn -V -e -B -ntp verify -Dmaven.javadoc.skip=false -DtrimStackTrace=false -Pit-tests,snapshot-validation -Dselenide.browserBinary=${{ steps.setup-chrome.outputs.chrome-path }}
    - name: End-to-end Tests (Production mode)
      shell: bash
      run: |
        set -x -e -o pipefail
        mvn -V -e -B -ntp verify -Dmaven.javadoc.skip=false -DtrimStackTrace=false -Pit-tests,production,snapshot-validation -Dselenide.browserBinary=${{ steps.setup-chrome.outputs.chrome-path }}
    - name: Checkout
      uses: actions/checkout@v3
      if: ${{ always() }}
      with:
        ref: ${{ inputs.original_ref }}
        fetch-depth: 0
