name: Update NPM dependencies
on:
  workflow_dispatch:
    inputs:
      target-branch:
        description: "Branch to update"
        required: true
        type: choice
        default: 'main'
        options:
          - main
          - "24.8"
          - "24.7"
          - "2.5"
          - "1.3"
  schedule:
    - cron: '0 2 * * *'
permissions:
  contents: read
jobs:
  compute-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Compute matrix
        id: set-matrix
        env:
          CMD_TARGET_BRANCH: ${{ inputs.target-branch }}
        run: |
          if [[ -z "$CMD_TARGET_BRANCH" ]]; then
            echo 'matrix={ "branch": ["main","24.8","24.7","2.5","1.3"] }' >> "$GITHUB_OUTPUT"
          else
            echo 'matrix={ "branch": ["'$CMD_TARGET_BRANCH'"] }' >> "$GITHUB_OUTPUT"
          fi
  update-npm-deps:
    permissions:
      pull-requests: write
      contents: write
    runs-on: ubuntu-latest
    needs: [compute-matrix]
    name: Update NPM dependencies
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.compute-matrix.outputs.matrix)}}
    steps:
      - name: Generate token
        uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2.1.0
        id: generate-token
        with:
          app_id: ${{ secrets.QUARKUS_HILLA_BOT_ID }}
          private_key: ${{ secrets.QUARKUS_HILLA_BOT_PRIVATE_KEY }}
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: refs/heads/${{ matrix.branch }}
          fetch-depth: 0
          token: ${{ steps.generate-token.outputs.token }}
      - name: Setup Java
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4.7.1
        with:
          java-version: 17
          distribution: 'temurin'
      - name: Search existing PR
        id: searchpr
        run: |
          existingPR=$(gh pr list --author "app/quarkus-hilla-bot" --json id,title,baseRefName,headRefName,number | \
            jq '.[] | select( .baseRefName == "${{ matrix.branch }}" and .headRefName == "chore/update_npm_deps_${{ matrix.branch }}" ) | .number')
          echo "prNumber=${existingPR:-0}" >> "$GITHUB_OUTPUT"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout and rebase PR
        if: ${{ steps.searchpr.outputs.prNumber != '0' }}
        run: |
          gh pr checkout ${{ steps.searchpr.outputs.prNumber }}
          git -c user.name="quarkus-hilla-bot[bot]" -c user.email="141157179+quarkus-hilla-bot[bot]@users.noreply.github.com" \
            rebase ${{ matrix.branch }}
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
      - name: Build
        run: |
          set -x -e -o pipefail
          mvn -V -e -ntp install -Pall-modules,production -DskipTests
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@b863ae1933cb653a53c021fe36dbb774e1fb9403 # v5.2.0
        id: commit-changes
        with:
          commit_message: "chore(npm-deps): update npm dependencies"
          commit_user_name: "quarkus-hilla-bot[bot]"
          commit_user_email: "141157179+quarkus-hilla-bot[bot]@users.noreply.github.com"
          commit_author: "quarkus-hilla-bot[bot] <quarkus-hilla-bot[bot]@141157179+users.noreply.github.com>"
          branch: "chore/update_npm_deps_${{ matrix.branch }}"
          create_branch: ${{ steps.searchpr.outputs.prNumber == '0' }}
          file_pattern: ':(glob)**/package*.json'
          push_options: '--force-with-lease'
      - name: Create PR
        if: ${{ steps.commit-changes.outputs.changes_detected == 'true' && steps.searchpr.outputs.prNumber == '0' }}
        run: |
          gh pr create --head chore/update_npm_deps_${{ matrix.branch }} --base ${{ matrix.branch }} \
            --title "chore(npm-deps): update npm dependencies (${{ matrix.branch }})" \
            --body "" --label "dependencies" >> "$GITHUB_STEP_SUMMARY" 2>&1
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
