name: Quarkus Hilla Validation
on:
  pull_request_target:
    types: [opened, synchronize, reopened, edited]
    paths:
      - README.md
      - LICENSE
      - .gitignore
      - etc/**
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "Validation not required"'